export const GET_MOSQUES_BY_LOCATION_PENDING = 'GET_MOSQUES_BY_LOCATION_PENDING';
export const GET_MOSQUES_BY_LOCATION_COMPLETED= 'GET_MOSQUES_BY_LOCATION_COMPLETED';
export const GET_MOSQUES_BY_LOCATION_REJECTED = 'GET_MOSQUES_BY_LOCATION_REJECTED';

export const GET_MOSQUE_TIMINGS_PENDING = 'GET_MOSQUE_TIMINGS_PENDING';
export const GET_MOSQUE_TIMINGS_REJECTED = 'GET_MOSQUE_TIMINGS_REJECTED';
export const GET_MOSQUE_TIMINGS_COMPLETED=  'GET_MOSQUE_TIMINGS_COMPLETED';

export const REFRESH_SELECTED_MOSQUE_PENDING = 'REFRESH_SELECTED_MOSQUE_PENDING';
export const REFRESH_SELECTED_MOSQUE_REJECTED = 'REFRESH_SELECTED_MOSQUE_REJECTED';
export const REFRESH_SELECTED_MOSQUE_FULLFILLED = 'REFRESH_SELECTED_MOSQUE_FULLFILLED'


export const POST_SELECTED_MOSQUE = 'POST_SELECTED_MOSQUE';
export const POST_FAVOURITE_MOSQUE = 'POST_FAVOURITE_MOSQUE';
export const REMOVE_MOSQUE = 'REMOVE_MOSQUE'
export const GET_SELECTED_MOSQUE = 'GET_SELECTED_MOSQUE';
export const SELECT_MOSQUE_START = 'SELECT_MOSQUE_START';
export const USER_PUSHED_TO_HOME =  'USER_PUSHED_TO_HOME';

export const CHANGE_TIME_FORMAT = 'CHANGE_TIME_FORMAT';
export const CHANGE_ACTIVE_LANGUAGE = 'CHANGE_ACTIVE_LANGUAGE';

export const CHANGE_SCHEDULE_NOTIFICATION = 'CHANGE_SCHEDULE_NOTIFICATION';